### ISSUE TITLE
Datapacks?

### ISSUE THREAD

**Issue by radiak1na** [TheAlienDoctor/minecraft-resource-pack-converter#17]
Is it possible at all to get datapacks to work? I have a Java resource and datapack for glowing armor trims but when I converted the datapack, 0 items were converted.

**Comment by TheAlienDoctor** [comment]
Unfortunately the automatic conversion of datapacks would be near impossible, due to the huge differences between them and Bedrock addons.

For example, converting a Bedrock mob heads addon to java would require making the textures uploaded and accessible via a url that's encoded in base64, then added to the respective mobs loot table as a skull dropping the the custom texture via the url.

... and that's just one example!

Don't worry if that didn't make sense, but the TL;DR automating datapacks would be near impossible due to the possibilities available with them.

-Alien
