### ISSUE TITLE
[question] Would this work with polymc?

### ISSUE THREAD

**Issue by vos6434** [TheAlienDoctor/minecraft-resource-pack-converter#2]
Would this work with resource packs generated by polymc?
https://github.com/TheEpicBlock/PolyMc

**Comment by TheAlienDoctor** [comment]
Hey, although I have not tested it, most of the textures generated from PolyMC will probably be able to be converted.
Bear in mind that this can only convert the actual texture (.png) files and not any json files.

Also as a sidenote I haven't officially announced the release of this program yet because I haven't made a video on how to use it yet, so if you do try using it I would check out either the instructions.txt file or wait for my vid. (Or you can join my Discord server and I can help you there :)

Thanks!

**Comment by vos6434** [comment]
Damn it wont show the custom textures on bedrock then.

**Comment by TheAlienDoctor** [comment]
I am not familiar with how PolyMC works, does it generate custom textures or just textures to replace existing ones?

**Comment by vos6434** [comment]
It generates custom textures and uses blockstates to show them.
Quote from PolyMc wiki.
"PolyMc uses block states that go unused on the client side to display modded blocks. This means there's a limit to how many blocks can be added. Here's an approximate, non-exhaustive, list of how many unused block states each collision shape has:

Full blocks: 971
Uncollidable blocks: 139 (can go up to 283)
Doors: 9
Trapdoors: 9
Path blocks: 5
Slabs: 5
Stairs: 4"

**Comment by TheAlienDoctor** [comment]
If it is **changing** vanilla textures that are availble in Bedrock yes, however if it is **creating** new textures then no.
