### ISSUE TITLE
Can't Convert  items(java) folder into bedrock

### ISSUE THREAD

**Issue by SagXD** [TheAlienDoctor/minecraft-resource-pack-converter#3]
Can't Convert  items(java) folder into bedrock

**Comment by TheAlienDoctor** [comment]
Hey, can you post a link here with the resource pack your trying to convert? 
Sorry for the slow reply, been a busy couple of days.

- Alien

**Comment by TheAlienDoctor** [comment]
Hey again, I have been unable to reproduce this issue on both converting JE to BE or BE to JE. Some items such as compass and clocks cannot be converted at this time due to formatting differences between versions so perhaps this is the issue you are running into?

I would recommend checking out #1 which also contains a list of unsupported textures.

-Alien
